baseURL = "https://example.org/"
languageCode = "en-us"
title = "Bonsai.css"
theme = "bonsai"

pygmentsUseClasses = true

BookSearch = false

googleAnalytics = "UA-167242421-1"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true