baseURL = "https://example.org/"
languageCode = "en-us"
title = "Bedrock.css"
theme = "bedrock"

pygmentsUseClasses = true

BookSearch = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true